### ISSUE TITLE
Check and approve for GO v1.5 readiness

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#102]
GO 1.5 was released with some major changes - please confirm romba OK to go

**Comment by uwedeportivo** [comment]
seems fine

it compiles, refresh-dats worked, archive worked, lookup worked. we can keep this open while you test some more.

**Comment by Obiwantje** [comment]
crashlog on dropbox - this is after an archive of an old depot folder - previous folder archvied without issue on v1.4

**Comment by uwedeportivo** [comment]
done
