### ISSUE TITLE
Implement for a romba.ini parameter that allows for raw (non .gz) storage

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#104]
Current behaviour: files are stored in the romba depot as .gz files (sha1.gz)

Requested behavior:
romba.ini
compressed_storage=no

files are stored in the romba depot as normal files (sha1) instead

User would have either/or environment.

Reason for this feature is to allow filesystems to take on task of compression and block de-duplication.

**Comment by uwedeportivo** [comment]
Not going to happen. Too many special cases. What about the metadata (the checksums stored in gz headers right now) ?

**Comment by Obiwantje** [comment]
Makes sense!
