### ISSUE TITLE
romba does not show the correct files being worked on in the web frontend

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#107]
It seems like romba shows the previous Y worker's files instead of the CURRENT files that romba is going through. This can be replicated easily by creating a Y x2  zip files with LOTS of small files in them and then looking at the web progress screen.

**Comment by uwedeportivo** [comment]
progress is not broken down at the level of contents of zip files

**Comment by Obiwantje** [comment]
I realise that - and that seems NOT to be this issue. Try this. Create 2x # of workers large files and do an archive command. It will NOT immediately show the first (say 4 workers) 4 files in the WEB progress window, it will show them AFTER they have been processed.
