### ISSUE TITLE
Add support for DOSCenter DATfile format

### ISSUE THREAD

**Issue by claunia** [uwedeportivo/romba#110]
Self-explaining

**Comment by Obiwantje** [comment]
This format which looks like this:

name "Arithmetic Games Set 1 [f1] (1981)(IBM, Science Research Associates) [Strategy, Educational].zip"
	file ( name !@#$%$#@.!@# size 4096 date 1981/08/04 00:00:00 crc 8f7abb81 )
	file ( name ARITHMET.BIN size 768 date 1981/07/17 00:00:00 crc 0a082568 )

This format will not be supported.
