### ISSUE TITLE
Remove restriction on '/' characters in header of a DAT

### ISSUE THREAD

**Issue by claunia** [uwedeportivo/romba#111]
Artificial restriction should be removed, there are a lot of datfiles with '/' characters.

**Comment by Obiwantje** [comment]
Claunia, make sure to put in your requests MORE elaborate - the developer is NOT a ROM guy, also properly tag the labels in github.

Feature Request:
Ignore (don't crash or consider faulty) the "/" sign when used in the DAT header ONLY
This applies to the <name> and <description> fields
eg:

?xml version="1.0"?>
<!DOCTYPE datafile PUBLIC "-//Logiqx//DTD ROM Management Datafile//EN" "http://www.logiqx.com/Dats/datafile.dtd">
<datafile>
	<header>
		<name>Arcade - Namco / Sega / Nintendo - Triforce</name>
		<description>Arcade - Namco / Sega / Nintendo - Triforce 20110418 14-54-01</description>
		<version>20110418 14-54-01</version>
		<date>20110418 14-54-01</date>
		<author>redump.org</author>
		<homepage>redump.org</homepage>
		<url>http://redump.org/</url>
	</header>

*Note - when using the BUILD or FIXDAT command, make sure that the "/" sign above is replaced by "-" to prevent the creation of additional folders.
