### ISSUE TITLE
Purge-backup is not working as intended when specifying a DAT as input

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#114]
Purge-backup is currently not working as intended when specifying a DAT as input.

romba, will instead of using the DB to determine which SHA1 files are no longer needed, to then backup those to the specified folder, go through ALL files and folders in ALL depots. - As a side-note, this IS the correct way of going about in case of NO DAT file is specified as input.

Behavior should be similar to a build command

**Comment by Obiwantje** [comment]
This is a user issue; the user needs to specify 'dat=' as part of the command for this to work

**Comment by uwedeportivo** [comment]
There's too many special cases with this romba stuff and I don't have that much time. For this particular command I reused the code path when no DAT is specified. I'm not going to change that and make another special case, sorry.

**Comment by Obiwantje** [comment]
Let me challenge that (while I do get your point r.e. lack of time)

Why not re-use the BUILD code path - as really it is an enhanced build:

(1) Seek if the ROMs exist
(2) Determine if any other DAT is using them
(3) If *NOT* build (and move) them from the depot 

Note: if easier - move the GZ file itself, instead of reconstructing it into the original ZIP format/path.

**Comment by uwedeportivo** [comment]
This makes no sense and is even more convoluted.

**Comment by Obiwantje** [comment]
This issue is resolved by using the external sabretools that allow to create a targeted list of files to be moved out of a depot
