### ISSUE TITLE
Add uncompressed size to the .gz header

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#121]
Primer:

rfc1952 describes the GZIP file format specification.
[https://tools.ietf.org/html/rfc1952](url)

Within this the following is of importance to this request

 2.2. File format

      A gzip file consists of a series of "members" (compressed data
      sets).  The format of each member is specified in the following
      section.  The members simply appear one after another in the file,
      with no additional information before, between, or after them.

   2.3. Member format
....
   (if FLG.FHCRC set)

         +---+---+
         | CRC16 |
         +---+---+

         +=======================+
         |...compressed blocks...| (more-->)
         +=======================+

           0   1   2   3   4   5   6   7
         +---+---+---+---+---+---+---+---+
         |     CRC32     |     ISIZE     |
         +---+---+---+---+---+---+---+---+

         CRC32 (CRC-32)
            This contains a Cyclic Redundancy Check value of the
            uncompressed data computed according to CRC-32 algorithm
            used in the ISO 3309 standard and in section 8.1.1.6.2 of
            ITU-T recommendation V.42.  (See http://www.iso.ch for
            ordering ISO documents. See gopher://info.itu.ch for an
            online version of ITU-T V.42.)

         ISIZE (Input SIZE)
            This contains the size of the original (uncompressed) input
            data modulo 2^32.

ISIZE is why this romba issue has been created.
According to RFC 1952, the recorded file size is stored in a 32-bit integer, therefore, it can not represent files larger than 4GB.

**Request:**

To aid the use of external tools

Insert/store the uncompressed data size in the header of the gz file similar to how currently the CRC32 and MD5 are inserted by romba, (offset 0xC - 0x1B -> MD5 and offset 0x1C - 0x1F -> CRC)

Store the correct uncompressed size in 64-bit integer format to overcome the 4GB limitation of the current RFC 1952 spec.

Note: 

(1)
It is understood that the current files in the depot do NOT have this size - no action is needed, an external conversion tool will fix these - out of scope for romba

(2)
For romba MERGE - please CHANGE the romba code so that the uncompressed size is picked up from the HEADER entry and no longer from isize

**Comment by uwedeportivo** [comment]
the header for .gz files in the depot does have the uncompressed size in 8 byte format 
the header is a byte slice with md5+crc+8byte size of file

**Comment by Obiwantje** [comment]
This has been confirmed as indeed the case. Case closed

**Comment by Obiwantje** [comment]
This issue is now re-opened. When using GZ files as an INPUT for archive - romba will mistakenly insert the COMPRESSED size in the header instead of the UNCOMPRESSED size. Normal files, ZIP files and 7ZIP files ARE handled correctly - the issue pertains specifically to GZ files as input
