### ISSUE TITLE
Add import / export CSV file to the keyvaultstore

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#122]
Please add a possibility to import a tab delimited csv file with size, sha1,md5,crc to the db - also allow for the export of such in the same format

Entries will have at a minimum a value for size AND (crc AND/OR md5 AND/OR sha1)

**Comment by uwedeportivo** [comment]
entries need to have sha1 otherwise it's impossible to resolve them in the depot.
the csv format needs a value for each column in a row otherwise csv parsers barf. NULL or NA or similar can be used for missing values. comma-separated is much more common than tab-separated.

**Comment by Obiwantje** [comment]
I stand corrected. The line should have read as follows:

All entries Entries will have at a a value for size AND MD5 AND SHA1

comma delimited and entries within " double quotes " is A-OK

**Comment by Obiwantje** [comment]
This will now be replaced by diff req
