### ISSUE TITLE
Update romba to work with GO 1.7

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#124]
romba will work successfully as-is when compiled against GO 1.6.3 - however the cgo wrapper broke with GO 1.7 - resulting in a non working archive command - crashing romba with a panic runtime error.

I0906 22:39:09.398431   14360 worker.go:366] found 359 files and 34 MiB to do. starting work...
I0906 22:39:09.398535   14360 worker.go:237] starting worker 3 for archive roms
I0906 22:39:09.398556   14360 worker.go:237] starting worker 0 for archive roms
I0906 22:39:09.398537   14360 worker.go:237] starting worker 1 for archive roms
I0906 22:39:09.398552   14360 worker.go:237] starting worker 2 for archive roms
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 45 [running]:
panic(0x83c7c0, 0xc420369b10)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/uwedeportivo/torrentzip/cgzip.(*Writer).SetExtraHeader(0xc420070800, 0xc420340fe0, 0x1c, 0x1c, 0x1000, 0x1000)

etc.. etc...

**Comment by uwedeportivo** [comment]
the etc..etc.. is actually important here. it seems to me that you're running old code. romba doesn't use torrentzip/cgzip anymore. i converted it to use klauspost, a pure go impl. i tried archiving with 1.7 and it worked.
