### ISSUE TITLE
Installation on macOS 10.11.6

### ISSUE THREAD

**Issue by Jakz** [uwedeportivo/romba#128]
Hello, I haven't been able to make it work on macOS 10.11.6.

I'm using [brew](https://brew.sh/) for all the dependencies, I'm able to launch `roombaserver` fine but all I get when browsing to http://localhost:4200/romba.html is a `404 page not found`, webserver is correctly up according to netstat:

    tcp46      0      0  *.4200                 *.*                    LISTEN

**Comment by Obiwantje** [comment]
Considered user error
