### ISSUE TITLE
Expand verbosity on errors in ediff command

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#150]
when ediff runs into parsing issues it will only give limited console feedback:
E1130 07:44:37.601428   18396 diffdat.go:339] error ediffdats: XML syntax error on line 16: attribute name without = in element

when running refresh-dats on the same it will ALSO show the affected filename - which will help in fixing the problem input file.

Please add same verbosity to ediff (and where else this may have been omitted)

**Comment by uwedeportivo** [comment]
re-opening, closed the wrong one
