### ISSUE TITLE
fixdat command stopped working

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#167]
> fixdat -out='/home/obi/romba/fixdats/obi_needs_031020-1' '/home/obi/dats/_collecting'
error: [object Object]

and in console:
2020/03/10 08:51:59 http: panic serving [::1]:56958: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc0000b0280)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x90cd00, 0xf7b1d0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/uwedeportivo/romba/service.(*RombaService).build(0xc00010c680, 0xc0000b6c60, 0xc001100df0, 0x1, 0x1, 0x0, 0x0)
	/home/thejay/go/src/github.com/uwedeportivo/romba/service/build.go:199 +0x1ed
github.com/uwedeportivo/commander.(*Command).Dispatch(0xc0000b6c60, 0xc001100dd0, 0x3, 0x3, 0x100000000000000, 0x3)
	/home/thejay/go/src/github.com/uwedeportivo/commander/commands.go:221 +0x240
github.com/uwedeportivo/commander.(*Command).Dispatch(0xc0000b6360, 0xc001100dc0, 0x4, 0x4, 0x0, 0x0)
	/home/thejay/go/src/github.com/uwedeportivo/commander/commands.go:187 +0x139
github.com/uwedeportivo/romba/service.(*RombaService).Execute(0xc00010c680, 0xc000188300, 0xc0005cd760, 0xc0005cd780, 0x0, 0x0)
	/home/thejay/go/src/github.com/uwedeportivo/romba/service/service.go:189 +0x243
reflect.Value.call(0xc00010c700, 0xc000100688, 0x13, 0x9a0085, 0x4, 0xc0000f7ae8, 0x4, 0x4, 0xc0000f7958, 0x49d7ad, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc00010c700, 0xc000100688, 0x13, 0xc0000f7ae8, 0x4, 0x4, 0x0, 0x7, 0x9c93d8)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/gorilla/rpc/v2.(*Server).ServeHTTP(0xc0001bc480, 0xa64b00, 0xc0001b0000, 0xc000188300)
	/home/thejay/go/src/github.com/gorilla/rpc/v2/server.go:220 +0xa3a
net/http.(*ServeMux).ServeHTTP(0xfc6b40, 0xa64b00, 0xc0001b0000, 0xc000188300)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0001b01c0, 0xa64b00, 0xc0001b0000, 0xc000188300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000b0280, 0xa661c0, 0xc001100000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

**Comment by uwedeportivo** [comment]
fixdat is a broken, deprecated command. marked it as deprecated in 186
