### ISSUE TITLE
Enhance keyvault to store if a file is present in depot

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#169]
Currently romba will aways check depot of availability of file - this creates for a very slow "build -fixdatOnly" command, as romba would need to check millions of entries depending on the DATroot. Please enhance romba that BY EXPLICIT CHOICE, romba instead can use a "last checked" stored value to indicates if the file is in a depot. 

Romba should ADD these entries also when the "archive" command is invoked, so that fixdat creations can be done from sole DB operation

**Comment by uwedeportivo** [comment]
i don't want to link the kv store with the file depot. it will be hard or impossible  to maintain the correctness of that bit in the kv store.  i was thinking it's better if i put a bloomfilter in front of the file depot. if you only use archive to add to the file depot, it should work well. the bloomfilter might give false positives but knows for sure if a file is not there. so even if you remove files from the depot without telling romba, the correctness of these semantics are preserved. it just assumes that adding to the file store is always done with archive. the bloomfilter has a small mem footprint, will fit in memory and will be superfast.

**Comment by Obiwantje** [comment]
Bloom functionality has now rendered this req no longer relevant
