### ISSUE TITLE
Have romba create a report of anticipated storage profile

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#82]
Requested feature

Request:
Use the individual 'ROM' size info obtained from the DAT files that are in the DB - to report out (in a text file) to allow user to profile the anticipated raw use of individual files. (So only those DATs that are current - not historic)

rom ( name "Animal Basket (anmlbskt).bin" size 67108864 crc 5a246d6b md5 59f44c687f34969ede1fa9791bf72ef4 sha1 946b61465121bc402078a4661276b5af2f25d2eb )

Reason:
Knowing an approximate storage profile will help setup and tune the underlying file-system correctly, as well as do some depot planning

Output requested (example)

13253 files in 0-2kb size
457493 files in the 2-4kb size
47568 files in the 4-8kb size
84368 files in the 8-16kb size
943683 files in the 16-32kb size
...

Requested is both txt and CSV format for further use.

**Comment by uwedeportivo** [comment]
New command "depotstats".
Output will look something like this:

> depotstats
number of roms=384277
rom size cumulative distribution = 
count, percentile, file size
2, 0.00000000, 0B
364069, 93.75000000, 171KiB
372271, 96.87500000, 638KiB
384119, 99.95117188, 19MiB
384184, 99.97558594, 29MiB
384231, 99.98779297, 570MiB
384254, 99.99389648, 704MiB
384266, 99.99694824, 723MiB
384272, 99.99847412, 740MiB
384275, 99.99923706, 742MiB
384276, 99.99961853, 745MiB
384277, 100.00000000, 747MiB
rom size histogram = 
count, file size
2, 0B
364067, 171KiB
8202, 638KiB
11848, 19MiB
65, 29MiB
47, 570MiB
23, 704MiB
12, 723MiB
6, 740MiB
3, 742MiB
1, 745MiB
1, 747MiB

You can copy/paste the lines into a csv file. First is the cumulative distribution, the second is its derivative.

**Comment by Obiwantje** [comment]
(1) Please add count of files <= 4KiB - this due to filesystems metafile inclusion parameter setup
(2) Add grand total storage space needed 

Are these values the de-duped space/counts?

**Comment by uwedeportivo** [comment]
not deduped, histogram is http://hdrhistogram.org/

**Comment by uwedeportivo** [comment]
deduped now
