### ISSUE TITLE
Check for romba DB crash cause

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#84]
This *could* be a result of a SSD error - but want to rule out

complete romba folder on dropbox - change paths in .ini and do a refresh-dats to see DB corruption errors flow in.

On the dropbox

**Comment by uwedeportivo** [comment]
I tried it. Unfortunately your db is corrupted. Not sure what I can do there.

**Comment by Obiwantje** [comment]
Thanks for checking - it seems that the SSD crash killed the DB
