### ISSUE TITLE
Romba fails (Hard crash) on 7z files during archive

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#92]
Example in the dropbox of a seemingly normal 7z file that hard crashes romba - it seems like most 7z files crash romba.

**Comment by Obiwantje** [comment]
This fix works almost completely as intended - BAD 7z files that fail to unpack though do NOT get copied to the "bad" folder despite romba claiming to do so:

E0623 11:30:15.163419   18156 worker.go:250] failed to process /mnt/roms01/(20150601 23-22-45)/Lomax (Japan).7z: exit status 2
I0623 11:30:15.163480   18156 worker.go:229] copying bad file /mnt/roms01/(20150601 23-22-45)/Lomax (Japan).7z to /mnt/roms01/depot.bad/(20150601 23-22-45)/Lomax (Japan).7z

**Comment by uwedeportivo** [comment]
That should be filed as a different bug. Do only corrupted 7z files not get copied over or is zip also not getting copied over ?

**Comment by Obiwantje** [comment]
I only have seen this happen with 7z, I have seen broken zip files being
copied over

**Comment by uwedeportivo** [comment]
This is the danger with running external commands. Probably someone is holding on to the file descriptor. I changed something in the 7z lib, maybe this will help. Try it
