### ISSUE TITLE
purge-backup command does ignores "-depot" option

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#99]
Despite specifying as specific path - romba will just start at root of the depot

eg.
purge-backup -backup -depot='/mnt/roms00/depot/45' purged_files

will just result in romba starting at '/mnt/roms00/depot/00'

**Comment by uwedeportivo** [comment]
it's a user error

purge-backup -backup -depot='/mnt/roms00/depot/45' purged_files

is parsed like this: since -backup is expected to have an argument, the next thing is its argument, so your backup directory is -depot='/mnt/roms00/depot/45'
means you never specify a depot with this string
